/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sasplanetj_Native */

#ifndef _Included_sasplanetj_Native
#define _Included_sasplanetj_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sasplanetj_Native
 * Method:    getZipFileNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sasplanetj_Native_getZipFileNative
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
